name: MSHV Build test
on: [pull_request, create]

jobs:
  build:
    name: Build test for MSHV crate
    strategy:
      matrix:
        platform:
          - target: x86_64-unknown-linux-gnu
            command: build

          - target: aarch64-unknown-linux-musl
            command: build

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--release"
